name = "MrGossett's Hyde"
license = "MIT"
description = "An elegant open source and mobile first theme"
tags = ["blog", "company"]
features = ["blog", ]

[author]
    name = "mrgossett"
    homepage = "http://mrgossett.com"

# If Porting existing theme
[original]
    author =  "mdo"
    repo = "http://www.github.com/mdo/hyde"
